image: ruby:3.0.2-bullseye

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8
  ALGOLIA_API_KEY: $ALGOLIA_API_KEY

before_script:
  - apt install curl
  - curl -fsSL https://deb.nodesource.com/setup_current.x | bash -
  - apt-get install -y nodejs
  - bundle install
  - npm install

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  - bundle exec htmlproofer --log-level :debug ./test --assume_extension --http_status_ignore 503 --url-ignore "/www.linkedin.com/,/www.dell.com/"
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  - bundle exec jekyll algolia
  artifacts:
    paths:
    - public
  only:
  - master
