image: ruby:3.0.2

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - bundle install

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
#  - bundle exec htmlproofer --log-level :debug ./test --assume_extension --http_status_ignore 503 --url-ignore "/www.linkedin.com/,/www.dell.com/"
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master

deploy_review:
  stage: deploy
  script:
    - echo "Deploy a review app"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.handbook.meltano.com
  only:
    - branches
  except:
    - master 
