# Custom Docker image based off of ruby:3.0.2-bullseye
image: registry.gitlab.com/meltano/handbook

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8
  ALGOLIA_API_KEY: $ALGOLIA_API_KEY

# This is technically taken care of in the Docker image but if someone installs new packages this should still find them.
before_script:
  - bundle install
  - npm install

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  - bundle exec htmlproofer --log-level :debug ./test --assume_extension --http_status_ignore 503 --disable_external true --url-ignore "/www.linkedin.com/,/www.dell.com/,/www.optionimpact.com/,/gusto.com/"
  - |
    git fetch origin $CI_DEFAULT_BRANCH;
    echo "Comparing to $CI_DEFAULT_BRANCH";
    REF="origin/${CI_DEFAULT_BRANCH}";
  - 'declare FILES=$(git diff --name-only ${CI_COMMIT_SHA} $REF | grep "\.md$")'
  - |
    if [ -n "${FILES}" ]; then
      echo "Changed files are\n$FILES";
      npx prettier -c $(echo $FILES | xargs);
    else
      echo "Nothing to lint"
    fi
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  - bundle exec jekyll algolia
  artifacts:
    paths:
    - public
  only:
  - master
