image: ruby:3.0.2

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - apt-get install npm
  - npm install
  - bundle install

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  - bundle exec htmlproofer --log-level :debug ./test --assume_extension --http_status_ignore 503 --url-ignore "/www.linkedin.com/,/www.dell.com/"
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
