# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Meltano Handbook
email: hello@meltano.com
description: > # this means to ignore newlines until "baseurl:"
  The Meltano Handbook is the open source company handbook for Meltano.
#baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://handbook.meltano.com" # the base hostname & protocol for your site
twitter_username: meltanodata
github_username:  meltano
gitlab_username:  meltano

# Outputting
permalink: /:categories/:year/:month/:day/:title

# Build settings
markdown: kramdown
exclude: ["README.md"]

defaults:
  - scope:
      path: ""
    values:
      toc: false # Don't show TOC by default. Set `toc: true` in Front Matter to override this.

# Every top level section of the handbook is actually a collection. Their files are in a _folder in src/
collections:
  engineering:
    output: true
    icon: "fa-cogs"
  marketing:
    output: true
    icon: "fa-chart-line"
  peopleops:
    output: true
    icon: "fa-user-cog"
  product:
    output: true
    icon: "fa-map-signs"
  resources:
    output: true
    icon: "fa-book"
  tech-stack:
    output: true
    icon: "fa-server"
  support:
    output: true
  posts:
    output: false

# The directory that contains file for our collections
collections_dir: src

# Add plugins here.
plugins:
  - jekyll-toc

# jekyll-toc Config
toc:
  min_level: 1
  max_level: 2
  ordered_list: false
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section-nav
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-
