# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Meltano Handbook
email: hello@meltano.com
description: > # this means to ignore newlines until "baseurl:"
  The Meltano Handbook is the open source company handbook for Meltano.
#baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://handbook.meltano.com" # the base hostname & protocol for your site
twitter_username: meltanodata
github_username:  meltano
gitlab_username:  meltano
github_repository: https://github.com/meltano/handbook

# Outputting
permalink: /:categories/:year/:month/:day/:title

# Build settings
markdown: kramdown
exclude: ["README.md"]

defaults:
  - scope:
      path: ""
    values:
      toc: true # Show TOC by default. Set `toc: false` in Front Matter to override this.

# Every top level section of the handbook is actually a collection. Their files are in a _folder in src/
collections:
  company:
    output: true
    icon: "fa-laptop-house"
    name: "Company"
  data-team:
    output: true
    icon: "fa-database"
    name: "Data Team"
  engineering:
    output: true
    icon: "fa-cogs"
    name: "Engineering"
  marketing:
    output: true
    icon: "fa-chart-line"
    name: "Marketing"
  peopleops:
    output: true
    icon: "fa-user-cog"
    name: "PeopleOps"
  product:
    output: true
    icon: "fa-map-signs"
    name: "Product"
  resources:
    output: true
    icon: "fa-book"
    name: "Resources"
  support:
    output: true
    icon: "fa-question-circle"
    name: "Support"
  posts:
    output: false

# The directory that contains file for our collections
collections_dir: src

# Add plugins here.
plugins:
  - jekyll-toc
  - jekyll-sitemap
  - jekyll-algolia

# jekyll-toc Config
toc:
  min_level: 1
  max_level: 2
  ordered_list: false
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section-nav
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-

# jekyll-algolia
algolia:
  application_id: 'N55Y9CP0EI'
  index_name: handbook_search
  search_only_api_key: '7d4f3fb94b8a6e1e0f262d626a9ff51f'

# Set display to true/false to toggle announcements on/off
announcement:
  display: true
  text: This December, we’re extracting trash to transform our waterways.
  cta: Learn more.
  cta-link: https://meltano.com/blog/extracting-trash-to-transform-our-waterways/
